name: ci-golang-workflow
on: [push]

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'  # Defina a versão adequada

      # - name: Install dependencies
      #   run: go mod tidy  # Baixar dependências

      - name: Run tests
        run: go test ./...  # Executa testes em todos os pacotes