name: Go CI/CD with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build Docker image
      run: docker build -t frankstark/goapp:latest .

    - name: Decode Docker credentials and login
      run: |
        echo ${{ secrets.DOCKER_AUTH }} | base64 -d | docker login -u frankstark --password-stdin

    - name: Push Docker image
      run: docker push frankstark/goapp:latest
